// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControYaApp.Models;

public partial class PrdOrdenProduccionNotificado
{
    public string CodigoProduccion { get; set; }

    public int Orden { get; set; }

    public string CodigoMaterial { get; set; }

    public int IdProduccion { get; set; }

    public DateTime Fecha { get; set; }

    public float Notificado { get; set; }

    public string CodigoUsuario { get; set; }

    public string CodigoTransaccion { get; set; }

    public int? Documento { get; set; }

    public int? FilaINV { get; set; }

    public string CodigoEmpleado { get; set; }

    public string Estado { get; set; }
}