// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControYaApp.Models;

public partial class PrdOrdenProduccion
{
    public string CodigoProduccion { get; set; }

    public int Orden { get; set; }

    public int? Ejercicio { get; set; }

    public int? Periodo { get; set; }

    public DateTime Fecha { get; set; }

    public string Referencia { get; set; }

    public string Detalle { get; set; }

    public string Estado { get; set; }

    public string CodigoUsuario { get; set; }

    public DateTime? FechaContabilizacion { get; set; }

    public string CodigoTipo { get; set; }
}